### ISSUE TITLE
Error Launching Application

### ISSUE THREAD

**Issue by arabestani** [sdtaheri/filimo-tvos#1]
hi
after opened app on the Xcode , set self sign and cert run app on simulator and show that message :Error Launching Application
The operation couldn't be completed. (TVMLKitErrorDomain error 3.) 
even I run ruby -run -ehttpd . -p9001 on terminal and show that log :
ERROR `/Application.js' not found.
::1 - - [21/May/2019:16:09:29 +0430] "GET //Application.js HTTP/1.1" 404 284
- -> /Application.js
pls help to fix this

**Comment by ghost** [comment]
This is a TVML JS app. It needs an HTTP server in Javascript folder. Check this out in `AppDelegate.swift` file in line 18.

```
    // tvBaseURL points to a server on your local machine. To create a local server for testing purposes, use the following command inside your project folder from the Terminal app: ruby -run -ehttpd . -p9001. See NSAppTransportSecurity for information on using a non-secure server.
    static let tvBaseURL: String = {
        #if DEBUG
            return "http://localhost:9001/"
        #else
            return "https://filimo.saeedtaheri.com/"
        #endif
    }()
```

If you're running it in Debug mode, you need a local HTTP server running on port 9001 in the JavaScript folder.

**Comment by arabestani** [comment]
I try that before u help, with 2 deferent command first ruby -run -ehttpd . -p9001 inside of project directory and second python -m SimpleHTTPServer 9001 but that error still on display.

**Comment by arabestani** [comment]
شرمنده اذیتتون میکنم 
بنده مد نویس نیستم شخصی میخواستم این ابزار و نصب کنم روی دیواسم، مشکل برای نمایش تو مک حل شده اما متاسفانه میزنم روی اول تی وی نشون بده باز همون ارور میاد، یعنی js زو نمیبینه

**Comment by ghost** [comment]
اگر برنامه‌نویس نیستید، کمک کردن به شما برای راه‌اندازی برای من مشکل است. 
اگر به جای حالت دیباگ، در حالت ریلیز اپ را روی دستگاهتان نصب کنید، نیاز به راه‌اندازی سرور نیست.

**Comment by ghost** [comment]
برای راه‌اندازی سرور باید در فولدر جاوااسکریپت، و نه فولدر پروژه، باشید.
